### ISSUE TITLE
Internal server error checking web of trust while installing a package

### ISSUE THREAD

**Issue by tyiu** [zapstore/zapstore-cli#16]
```
% ./zapstore install apktool
Successfully updated zapstore to 0.0.5!

✔ Found apktool@2.9.3 (released on 2024-08-22T06:38:42.000)
  A tool for reverse engineering Android apk files

Your npub will be used to check your web of trust before installing any new packages

If you prefer to skip this, leave it blank and press enter to proceed to install
✔ npub · npub1yaul8k059377u9lsu67de7y637w4jtgeuwcmh5n7788l6xnlnrgs3tvjmf        
⠇ Checking web of trust...
ERROR FormatException: Unexpected character (at character 1)
Internal server error
^



#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      jsonDecode (dart:convert/json.dart:155)
#7      R2.getJson (package:zapstore_cli/utils.dart:130)
<asynchronous suspension>
#8      install (package:zapstore_cli/commands/install.dart:151)
<asynchronous suspension>
#9      InstallCommand.run (package:zapstore_cli/main.dart:73)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#11     main (package:zapstore_cli/main.dart:34)
<asynchronous suspension>
```

**Comment by franzaps** [comment]
Added a handler for remote server errors
