### ISSUE TITLE
Websocket is not connected

### ISSUE THREAD

**Issue by learntheropes** [zapstore/zapstore-cli#31]
By running
```
APKSIGNER_PATH=/home/learntheropes/Android/Sdk/build-tools/34.0.0/apksigner zapstore publish peach --overwrite-release
 ```
I get
```
ERROR WebSocket is not connected.

#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011)
#1      WebSocket.connect (dart:_http/websocket.dart:320)
#2      WebSocketClient$VM.connect (package:ws/src/client/ws_client_vm.dart:102)
#3      WebSocketClient.connect.<anonymous closure>.<anonymous closure> (package:ws/src/client/ws_client.dart:116)
#4      new Future.sync (dart:async/future.dart:313)
#5      WebSocketClient.connect.<anonymous closure> (package:ws/src/client/ws_client.dart:116)
#6      WebSocketTask.call (package:ws/src/util/event_queue.dart:88)
#7      WebSocketEventQueue._exec.<anonymous closure> (package:ws/src/util/event_queue.dart:56)
#8      Future.doWhile.<anonymous closure> (dart:async/future.dart:720)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#10     _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1633)
#11     Future.doWhile (dart:async/future.dart:735)
#12     WebSocketEventQueue._exec (package:ws/src/util/event_queue.dart:50)
#13     WebSocketEventQueue.push (package:ws/src/util/event_queue.dart:20)
#14     WebSocketClient.connect (package:ws/src/client/ws_client.dart:110)
#15     WebSocketPool.initialize (package:purplebase/src/pool.dart:29)
#16     RelayMessageNotifier.initialize (package:purplebase/src/relay.dart:115)
#17     publish (package:zapstore_cli/commands/publish.dart:47)
<asynchronous suspension>
#18     PublishCommand.run (package:zapstore_cli/main.dart:175)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#20     main (package:zapstore_cli/main.dart:37)
<asynchronous suspension>
```
What could be the issue?

**Comment by ildella** [comment]
I get `ERROR WebSocket is not connected.` just by running `zapstore install myapp.apk`

**Comment by franzaps** [comment]
Which version are you running? `zapstore -v`

**Comment by learntheropes** [comment]
zap.store 0.1.0

**Comment by franzaps** [comment]
Makes sense! 0.1.0 points to `relay.zap.store` which obviously is down. Please upgrade to 0.1.2 . https://zapstore.dev/download

In general, please try to make sure you are running the latest.

**Comment by learntheropes** [comment]
I switch with
`git checkout 0.1.2`
but I'm still on `zap.store 0.1.0`
How to fix?

**Comment by franzaps** [comment]
I'm confused - you pull the code but what are you running?

I suggest the following IF you want to run from source:

```
git pull origin
git checkout 0.1.2
dart pub get
dart compile exe lib/main.dart -o zapstore-0.1.2
chmod +x zapstore-0.1.2
./zapstore-0.1.2
```

Once you run a new version of the program for the first time, it will auto-install itself. So at this point you can start using `zapstore` from your PATH. `zapstore -v` should return 0.1.2

If you run into version problems for whatever reason, try `rm -f ~/.zapstore/zapstore` and again

**Comment by learntheropes** [comment]
So, I'm running it from scratch:
```
git clone https://github.com/zapstore/zapstore-cli.git
cd zapstore-cli
git checkout 0.1.2
dart pub get
dart compile exe lib/main.dart -o zapstore-0.1.2
chmod +x zapstore-0.1.2
./zapstore-0.1.2
```
But when I run `zapstore -v` I get:
```
bash: /home/learntheropes/.zapstore/zapstore: No such file or directory
```

**Comment by franzaps** [comment]
Sorry, my mistake I think: try `./zapstore-0.1.2 list` - that should install. If it doesn't work please paste the output of the command here
